# Generated by Django 3.2.6 on 2022-10-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to='products', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(upload_to='avatars', verbose_name='image'),
        ),
    ]
